pipeline {
    agent any

    environment {
        GITHUB_REPO = 'https://github.com/freedal96/DevOpsTask.git'
        DOCKER_IMAGE = 'freedalelan/webapp'
        DOCKER_TAG = "${env.BUILD_ID}"
        HELM_CHART_PATH = 'helm/'
        PATH = "$HOME/.local/bin:$PATH"
    }

    stages {

        stage('Build Docker Image') {
            steps {
                sh '''
                    cd app
                    docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} .
                '''
            }
        }

        stage('Test Docker Image /health') {
            steps {
                sh '''
                    docker rm -f tempweb || true
                    docker run -d --name tempweb -p 8000:8000 ${DOCKER_IMAGE}:${DOCKER_TAG}
                    sleep 5
                    curl -f http://localhost:8000/health || (echo "Health check failed" && exit 1)
                    docker stop tempweb
                    docker rm tempweb
                '''
            }
        }

        stage('Push Docker Image to DockerHub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker', usernameVariable: 'DH_USER', passwordVariable: 'DH_PASS')]) {
                    sh '''
                        echo $DH_PASS | docker login -u $DH_USER --password-stdin
                        docker push ${DOCKER_IMAGE}:${DOCKER_TAG}
                        docker tag ${DOCKER_IMAGE}:${DOCKER_TAG} ${DOCKER_IMAGE}:latest
                        docker push ${DOCKER_IMAGE}:latest
                    '''
                }
            }
        }

        stage('Install Helm') {
            steps {
                sh '''
                    mkdir -p $HOME/.local/bin
                    curl -fsSL https://get.helm.sh/helm-v3.19.0-linux-amd64.tar.gz -o helm.tar.gz
                    tar -zxvf helm.tar.gz
                    mv linux-amd64/helm $HOME/.local/bin/helm
                    chmod +x $HOME/.local/bin/helm
                    helm version
                '''
            }
        }

        stage('Deploy to Kubernetes via Helm') {
            steps {
                withCredentials([file(credentialsId: 'kubeconfig-file', variable: 'KUBECONFIG_PATH')]) {
                    sh '''
                        export KUBECONFIG=$KUBECONFIG_PATH
                        cd helm
                        helm upgrade --install webapp . \
                            --set image.repository=${DOCKER_IMAGE} \
                            --set image.tag=${DOCKER_TAG}
                    '''
                }
            }
        }
    }

    post {
        always {
            sh 'docker system prune -f || true'
        }
        success {
            echo "✅ Deployment completed successfully!"
        }
        failure {
            echo "❌ Deployment failed!"
        }
    }
}